version: "3.8"
services:
  application:
    container_name: football_app
    image: mmalik/football_app:latest
    build: .
   ports:
    - target: 5000
      published: 80
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:
    database:
      container_name:
      image: 
      environment:
        MYSQL_ROOT_PASSWORD:
        MYSQL_DATABASE: football


