version: "3.8"
services:
  football-app:
    container_name: football_app
    image: mmalik18/football_app:latest
    build: .
    ports:
    - published: 80
      target: 5000 
    environment:
      DATABASE_URI: mysql+pymysql://root:${MYSQL_ROOT_PASSWORD}@football_database:3306/football
      CREATE_SCHEMA:
    depends_on:
    - database
  database:
    container_name: football_database
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: football
    volumes:
    - type: volume
      source: football_database_volume
      target: /var/lib/mysql
volumes:
  football_database_volume:


