pipeline {
    agent any
    environment{
        DOCKER_HUB_CREDS = credentials("DOCKER_HUB_CREDS")
        DOCKER_HUB_PASSWORD = credentials("DOCKER_HUB_PSW")
    }
    stages {
        stage('Setup') {
            steps {
                sh "bash jenkins/setup.sh"
            }
        }
        stage('Test') {
            steps {
                sh "bash jenkins/test.sh"
            }
        }
        stage('Build') {
            steps {
                sh "bash jenkins/build.sh"
            }
        }
        stage('Push') {
            steps {
                sh "bash jenkins/push.sh"
            }
        }
        stage('Deploy') {
            steps {
                sh "bash jenkins/deploy.sh"
            }
        }
    }
}